[package]
name = "asset-squisher"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24", features = ["avif"] }
thiserror = "1"
walkdir = "2"
zstd = "0.13"
brotli = "3"
flate2 = "1"
webp = "0.2"
